export enum ErrorCode {
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
  IDENTIFIER_NOT_FOUND = 'IDENTIFIER_NOT_FOUND',
  MISSING_IDENTIFIER = 'MISSING_IDENTIFIER',
  UNNECESSARY_IDENTIFIER = 'UNNECESSARY_IDENTIFIER',
  SERVICE_NOT_APPLICABLE = 'SERVICE_NOT_APPLICABLE',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  // Customer Insights specific error codes
  'CUSTOMER_INSIGHTS.SCALE_TYPE_NOT_SUPPORTED' = 'CUSTOMER_INSIGHTS.SCALE_TYPE_NOT_SUPPORTED',
  'CUSTOMER_INSIGHTS.INVALID_IDENTIFIERS' = 'CUSTOMER_INSIGHTS.INVALID_IDENTIFIERS',
  'CUSTOMER_INSIGHTS.ID_DOCUMENT_NOT_SUPPORTED' = 'CUSTOMER_INSIGHTS.ID_DOCUMENT_NOT_SUPPORTED',
  'CUSTOMER_INSIGHTS.ID_DOCUMENT_REQUIRED' = 'CUSTOMER_INSIGHTS.ID_DOCUMENT_REQUIRED',
}
